input {
  rabbitmq {
    host     => "${RABBITMQ_HOST:rabbitmq}"
    port     => 5672
    user     => "${RABBITMQ_USER:guest}"
    password => "${RABBITMQ_PASS:guest}"
    queue     => "logs"
    durable   => true
    ack       => true
    codec     => "json"
    arguments => {"x-dead-letter-exchange" => "logs.dlx"}
  }
}

output {
  elasticsearch {
    hosts => ["${ELASTICSEARCH_URL:http://elasticsearch:9200}"]
    index => "subber-logs-%{+YYYY.MM.dd}"
  }
}
