name: 'Test: Architecture'

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    name: Run Architecture Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: false

      - name: Test architecture dependencies
        run: go test -v ./tests/architecture/...
